### ISSUE TITLE
Missing sandbox & template directory

### ISSUE THREAD

**Issue by stephanebarbey** [ipselon/sdr-bootstrap-prepack#1]
I get the following error when running npm install && structor
```
$ npm install && structor
npm WARN sdr-bootstrap-prepack@0.0.0 No repository field.
npm WARN sdr-bootstrap-prepack@0.0.0 No license field.
Error happened during server initialization:
Error: ENOENT: no such file or directory, stat '/Users/stephane/Devel/structor/sdr-bootstrap-prepack-master/.structor/sandbox'
Error: ENOENT: no such file or directory, stat '/Users/stephane/Devel/structor/sdr-bootstrap-prepack-master/.structor/sandbox/template'
```
and the error 

```
Error happened during server initialization:
The paths section is missing in the current project configuration.
```
if I create the missing directories by hand. Any idea what went wrong?

**Comment by ipselon** [comment]
@stephanebarbey this project is frozen and is not compatible with the latest version of Structor. It works with Structor v0.2.9

**Comment by stephanebarbey** [comment]
Thanks for your prompt answer. I was able to start structor.
You may with to update the install documentation to run
`npm install structor@0.2.9 -g`
instead of `npm install structor -g`
(But thanks a lot anyway!)
