### ISSUE TITLE
Unable to get the project up and run

### ISSUE THREAD

**Issue by sic99** [ipselon/sdr-bootstrap-prepack#2]
I tried both methods  but no luck as I cannot get this project up and run. Method 1, download archive file, but error displayed 'no such file or directory stat '/generator/sdr-bootstrap-prepack-master/.structor/sandbox'.  Method 2,  I cannot find sdr-bootstrap-prepack project from project gallery. Please advise.

**Comment by ipselon** [comment]
this project is compatible with version 0.2.9
